# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d132c30cdc71ffc4e32c22cf5acd0cad0f769df13523e14aa508626f0e918412283bc42ad3e177bd37a31118ed64670a0423e71c89c21e2132ffde176d9cad55

test:
  secret_key_base: 51ca9af4b8235d69f6d52605cf897942a73d6b30b65cbb15a95fa1f57157311b54784a518da916a5b4a6ea8999eefedb717a49b94af93615774879eddab07210

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
